name: "On commit"

on: push

jobs:
  linting:
    name: Linting
    uses: PossibleLlama/workflows/.github/workflows/golang-linting.yaml@v0.2.13
    with:
      source-path: "./..."

  test-small:
    name: Test small
    uses: PossibleLlama/workflows/.github/workflows/golang-testing-small.yaml@v0.2.13
    with:
      enable-performance: true
      enable-fuzz: false
