name: "On commit"

on: push

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"

    - name: Check formatting
      run: go fmt ./...

    - name: Check vet
      run: go vet ./...

    - name: Check linting
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-pkg-cache: true
        args: --issues-exit-code=0 --out-format checkstyle -v ./... > ./lint.out

    - name: Store linting report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Linting report
        path: ./lint.out
        if-no-files-found: ignore
        retention-days: 2

  test-small-correctness:
    name: Small Tests - Correctness
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"

    - name: Get dependencies
      run: go mod download && go install gotest.tools/gotestsum@latest

    - name: Correctness tests
      run: gotestsum --packages="./..." --junitfile="./correctness-tests.xml" -- -coverprofile="./correctness-tests-coverage.out" -count=10 -race

    - name: Store test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test small reports
        path: |
          ./correctness-tests.xml
          ./correctness-tests-coverage.out
        if-no-files-found: ignore
        retention-days: 2

  test-small-performance:
    name: Small Tests - Performance
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: "./go.mod"

    - name: Get dependencies
      run: go mod download

    # TODO Add test for on PR, run performance test on HEAD and PR, and check diff
    - name: Performance tests
      run: go test -bench="." -count=10 ./... > ./performance-tests.txt

    - name: Store test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: Test small performance reports
        path: ./performance-tests.txt
        if-no-files-found: ignore
        retention-days: 2
