name: "On commit - Main"

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: "lts/*"

    - name: Semantic Release
      run: |
        npm i @semantic-release/commit-analyzer @semantic-release/git @semantic-release/changelog conventional-changelog-conventionalcommits
        npx semantic-release@21
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
