name: "Security scans"

on: push

jobs:
  SCA:
    name: SCA
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v3
      with:
        go-version: ^1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Write Go List
      run: go list -json -m > go.list

    - name: Run Nancy
      uses: sonatype-nexus-community/nancy-github-action@main

  SAST:
    name: SAST
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...

  VulnCheck:
    name: VulnCheck
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Download GoVulnCheck
        run: go install golang.org/x/vuln/cmd/govulncheck@latest
      
      - name: Run GoVulnCheck
        run: govulncheck ./... || true
